### ISSUE TITLE
Stages issues

### ISSUE THREAD

**Issue by Lklkjddjd** [qingjun1991/GameDreamFactory#17]
There are some stages that have a pink texture and do not have a floor.
For example this:
![Screenshot_20240601-170101](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/f29528f1-63a2-4052-9a1e-c50d7b0a8660)

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the "!GameDreamFactory\CQJ.Libs\GameDreamFactory.Core.dll"!

**Comment by Lklkjddjd** [comment]
Thank you very much

**Comment by Lklkjddjd** [comment]
There is another bug that is that when I press the back button and want to enter again it does not work example:

https://github.com/qingjun1991/GameDreamFactory/assets/171199696/e484ac92-71b2-453a-a7c9-b8e993e31ca5

**Comment by qingjun1991** [comment]
There is no such problem in general. This can only happen if the application takes up too much running memory. This is controlled by the mobile operating system, not by the app.

**Comment by Lklkjddjd** [comment]
Okey anyway thanks you very much

**Comment by Lklkjddjd** [comment]
There is a small bug that makes it impossible to read the origins of the characters, there are only the images but not the character's story example:
![Screenshot_20240602-001841](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/6fb7d607-add3-47e0-89ea-1281e08219d6)
![Screenshot_20240602-001855](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/92ce67f5-5bc5-4ee8-9011-9e2cb9ea9385)

**Comment by qingjun1991** [comment]
Please provide a detailed explanation of your operation process.

**Comment by Lklkjddjd** [comment]
What do you mean?

**Comment by qingjun1991** [comment]
Because I don't know how to reproduce the problem you mentioned.

**Comment by Lklkjddjd** [comment]
Here Is a way of how reproduce the problem

Uploading XRecorder_Edited_02062024_102812.mp4…

**Comment by Lklkjddjd** [comment]
https://github.com/qingjun1991/GameDreamFactory/assets/171199696/6ca7bb70-38c4-44e7-8a52-9d9350134e7b

**Comment by Lklkjddjd** [comment]
By the way this is another game
https://mega.nz/file/xugnXYRI#IBV5OQJSuAjIH303XkrNuVBMLUfu5oq3M9uAgFEsZZk

**Comment by qingjun1991** [comment]
This link cannot be accessed in our country. If it is a compatibility issue with characters, can you send me one of the character packages?

**Comment by Lklkjddjd** [comment]
https://www.mediafire.com/file/a38yo0welbl7iis/MKP_Expanded_Plus.rar/file
Here Is a other link

**Comment by Lklkjddjd** [comment]
https://www.mediafire.com/file/a38yo0welbl7iis/MKP_Expanded_Plus.rar/file

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the "!GameDreamFactory\CQJ.Libs\GameDreamFactory.Core.dll"!

**Comment by Lklkjddjd** [comment]
Thanks you very much

**Comment by Lklkjddjd** [comment]
There is other bug in some stages that causes the camera to not follow the character when there is a transition to another stage 
Example:


https://github.com/qingjun1991/GameDreamFactory/assets/171199696/158320f8-8f8e-465a-8c3c-c20f131fad6d

The stage Is called bank
Is the stage 25

**Comment by qingjun1991** [comment]
The problem has been resolved, please update the "!GameDreamFactory\CQJ.Libs\GameDreamFactory.Core.dll"!

**Comment by Lklkjddjd** [comment]
Thanks you very much

**Comment by Lklkjddjd** [comment]
There is a bug that causes the running bars to not stay in place and move out of place
Example:
![Screenshot_20240603-211134](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/c8dc6d9c-fb5f-4147-9376-65a2c10ca839)

and there are a bug with some stages that prevent some textures from loading
Example:
![Screenshot_20240603-210822](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/9e3a1e2a-1892-4bcf-9a74-13c42eda3986)
 

![Screenshot_20240603-195433](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/6b59a2ae-39b8-4694-ae95-524933ddf17a)

This Is the stages 81 called Nexus 

This Is from mortal Kombat expanded plus

**Comment by qingjun1991** [comment]
1, The same code has different running effects in different versions of Mugen. In order to simulate these effects, "Mugenversion=xxx" is used to distinguish them. In this case, it is the effect of Mugen1.1, so you need to modify all character pack .def file "Mugenversion=1.0" to "Mugenversion=1.1".

2, If special parameters are used in the stage, it will not be possible to simulate and this problem I cannot be solved.

3, You can delete the garbled characters in the stage .def file to solve it.
Alternatively, you can modify the .cfg file [Config] by changing "IdentifyEncoding=1" to "IdentifyEncoding=0" to resolve the issue.

**Comment by Lklkjddjd** [comment]
Okay i understand thanks you very much

**Comment by Lklkjddjd** [comment]
Also some stages like sewer do not generate background

**Comment by qingjun1991** [comment]
like 3, You can delete the garbled characters in the stage .def file to solve it.
Alternatively, you can modify the .cfg file [Config] by changing "IdentifyEncoding=1" to "IdentifyEncoding=0" to resolve the issue.

**Comment by Lklkjddjd** [comment]
Ok thanks you very much

**Comment by Lklkjddjd** [comment]
Almost everything is working now without bugs
There is only the problem of the stages with 3D effects

**Comment by Lklkjddjd** [comment]
By the way This Is the stage 81

**Comment by Lklkjddjd** [comment]
Also this Is the stage 131
![Screenshot_20240605-062342](https://github.com/qingjun1991/GameDreamFactory/assets/171199696/85fc90e6-8a2e-4b04-8c9f-09b3a1c41863)

**Comment by qingjun1991** [comment]
I have answered all the questions you mentioned above, and I have also solved all the problems that have solutions. Is there anything you don't understand?

**Comment by Lklkjddjd** [comment]
Yeah how i can delete the garbled character and how i can modify the cfg file?

**Comment by qingjun1991** [comment]
This is a problem caused by text file encoding, In the Mugen world, there has always been an issue with text file encoding, which causes many characters and stages to be unable to be used normally in other countries. To solve this problem, GameDreamFactory has added Identify Encoding function, which solves most of the problems. However, if the file contains many incorrect characters, the program is also powerless.



Solution 1:
Choose this stage and enter the battle, Follow the steps in the picture to find the location of the stage .def file.
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/f08b2675-e44c-4db7-86cb-b5fceaa82f3b)
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/86c38ec7-9fd5-4476-a3d2-91bc986534e1)
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/1c58d4fd-708b-4475-abde-620364ed138e)

open "stages/MK6/The_Nexus.def", You can see these garbled characters, you can simply delete them, [BG xxx] to [BG].
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/bea7c26e-23f6-4b14-a53b-949319594063)



Solution 2:
open "data/Main.cfg" or "data/mugen.cfg",  Find "[Config]", Add or modify "IdentifyEncoding=0".



result:
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/ebb50ff0-da5c-447b-a0f3-dcab73257704)

**Comment by qingjun1991** [comment]
This is a problem caused by text file encoding, In the Mugen world, there has always been an issue with text file encoding, which causes many characters and stages to be unable to be used normally in other countries. To solve this problem, GameDreamFactory has added Identify Encoding function, which solves most of the problems. However, if the file contains many incorrect characters, the program is also powerless.

Solution 1:
Choose this stage and enter the battle, Follow the steps in the picture to find the location of the stage .def file.
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/a150b017-d3aa-4653-8965-5c79c9f6e8ae)
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/0ad761b0-b5d0-492c-9b41-055e867d4149)
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/f0e1758c-e064-454a-8a08-2f39913a8b31)
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/5bd7f36c-bc7c-4ae6-8726-a2c9e5e78fd8)



open "stages/MK6/The_Nexus.def", You can see these garbled characters, you can simply delete them, [BG xxx] to [BG].
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/6032bda0-6af4-40f9-ba02-ea18a1ddbb24)

Solution 2:
open "data/Main.cfg" or "data/mugen.cfg", Find "[Config]", Add or modify "IdentifyEncoding=0".

result:
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/af44d347-8ac5-4c7f-b59b-952bfff03b36)

**Comment by Lklkjddjd** [comment]
I tried but didnt work

**Comment by qingjun1991** [comment]
Please send me your modified file for me to review.

**Comment by Lklkjddjd** [comment]
Here Is the stage def
https://www.mediafire.com/file/vl8w0lncct1xc5o/The_Nexus.def/file
And the main cfg
https://www.mediafire.com/file/p71w5tk4h5okmdg/Main.cfg/file

**Comment by qingjun1991** [comment]
1, "[BGdef]" here's no incorrect characters, you don't need to modify it, and this is the key word, can not modify it.

2, Why did you add "+IdentifyEncoding=0"?

**Comment by Lklkjddjd** [comment]
previously I accidentally removed the identify encoding

**Comment by Lklkjddjd** [comment]
Now some stage Is working like the stage 81

But the stage 131 still bugs

**Comment by Lklkjddjd** [comment]
https://www.mediafire.com/file/tu7p1k7w75nwoy8/The+Blue+Portal+Otherside+2.def/file

Here Is the def file

**Comment by qingjun1991** [comment]
I have already answered you earlier.

2, If special parameters are used in the stage, it will not be possible to simulate and this problem I cannot be solved.

**Comment by qingjun1991** [comment]
Because I don't have the source code for Mugen, I can't do all the functions of Mugen. 
And the goal of this software is not to make it an engine like mugen, You can't treat it as a mugen.

**Comment by Lklkjddjd** [comment]
Anyway thanks you very much for all your help and patience

**Comment by Lklkjddjd** [comment]
This Is closed for now

**Comment by qingjun1991** [comment]
> previously I accidentally removed the identify encoding
You don't seem to understand. I mentioned earlier that "IdentifyEncoding=0", but you used "+IdentifyEncoding=0", which of course has no effect. They are obviously different.

**Comment by qingjun1991** [comment]
> previously I accidentally removed the identify encoding

You don't seem to understand. I mentioned earlier that "IdentifyEncoding=0", but you used "+IdentifyEncoding=0", which of course has no effect. They are obviously different.

**Comment by Lklkjddjd** [comment]
Yeah i know now the stages with 3D effects work perfectly

**Comment by Lklkjddjd** [comment]
Yeah i know now the most of stages with 3D effects work perfectly
