### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Lklkjddjd** [qingjun1991/GameDreamFactory#18]
There is a bug that causes the game to never start and only the music can be heard

This Is the game link:
http://www.mediafire.com/file/z9yyxhi3014kv6d/%257EMKP_TAG%257E.zip/file

**Comment by qingjun1991** [comment]
This link requires a password to download.

**Comment by Lklkjddjd** [comment]
The password Is mkaddict2020

**Comment by qingjun1991** [comment]
I am unable to reproduce your issue on my phone.

![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/1a67e8b6-4705-4230-b941-600c452f4da7)

Take a look at the content of "!GameDreamFactory/log.txt".

**Comment by Lklkjddjd** [comment]
What I mean is that when I press a button the game crashes and never starts


https://github.com/qingjun1991/GameDreamFactory/assets/171199696/7fd62ff1-9344-40e7-87e4-8d3de892448a

**Comment by qingjun1991** [comment]
I am unable to reproduce your issue on my phone.
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/aab9d7da-4f81-484b-86e5-51f2e40fdf3b)

1, If the app does not automatically exit, it indicates that it is loading files and can be played after the loading is completed,

2. If the app automatically exits, it indicates that the Android system believes that the app has taken up too much running memory and forcibly ended the app process. This is controlled by the Android system and not by the app. You can remove some characters so that you can play.

 
笔记

**Comment by Lklkjddjd** [comment]
thanks you now works
