### ISSUE TITLE
Stage running at low fps

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#19]
https://mugenarchive.com/forums/downloads.php?do=file&id=113623-f-zero-mute-city-i-agnibyte

This stage is running in low fps, different from the other stages, and i don't know why

**Comment by qingjun1991** [comment]
![image](https://github.com/qingjun1991/GameDreamFactory/assets/44547439/91e3d057-ff23-4048-8963-11440d6b8c7e)
The first time I tried it on my phone, it was 60 fps, and then I tried it again, it was 30fps. This should be caused by the phone overheating.

There are 507 [BG ***] in "f-zero_mute_city1pI.def", which means that this stage alone needs to draw 60 * 507=30420 [BG ***] per second, it's too crazy, so it's a bit slow.

**Comment by NuggetFangus** [comment]
So no fix for now?

**Comment by qingjun1991** [comment]
Since it's a problem with the stage, you should go find the author of the stage to optimize it.
