### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#22]
Will you add support to add004 and Fighter Factory? So we can modify mugen

**Comment by qingjun1991** [comment]
No, Because Game Dream Factory is not a Windows emulator.  You can install Windows emulator to run add004 and Fighter Factory.

**Comment by NuggetFangus** [comment]
Is there any way to disable gamedreamfactory's Player Count? Because it becomes invisible in some screenpacks

**Comment by qingjun1991** [comment]
If you are playing arcade mode, modify the .cfg file:
SelectPlayerCountMax=1



Other modes do not provide setting options. This is to avoid players frequently modifying this setting.

Solution 1: You can press Left before confirming the player count, until there is no sound, indicating that the player count is 1.

Solution 2: Search and modify the teammenu in system.def to display the player count.

**Comment by NuggetFangus** [comment]
Actually i realized that the player count is out of screen, like its bugged or something, so i dont know how to fix it

**Comment by qingjun1991** [comment]
This is the same as Mugen adjusting the teammenu in system.def

**Comment by NuggetFangus** [comment]
Thank you very much for the help!

**Comment by NuggetFangus** [comment]
Is game dream factory compatible with anti ghosting? Because i have an anti ghosting keyboard but the anti ghosting doesnt work on game dream factory, so i cant press 2 button at the same time

**Comment by qingjun1991** [comment]
Can all other buttons be used normally except for press 2 button at the same time?

**Comment by NuggetFangus** [comment]
Yes

**Comment by qingjun1991** [comment]
Modify .cfg file:
ModifyInput=2

**Comment by NuggetFangus** [comment]
YOOOO IT WORKS, THANK YOU SO MUCH, I HAD THIS PROBLEM FOR A LONG TIME

**Comment by NuggetFangus** [comment]
Is there any way to load the chars before the fight? Because some chars have a lot of sprites and effects and it stops for some seconds to load mid fight

**Comment by qingjun1991** [comment]
Solution 1:
Modify .cfg file:
StartLoadAllResource=

Solution 2:
In the VS screen, pressing the Start button (on the keyboard is G) will load all the images of the selected character and stage, making the battle process very smooth; The Start button is equivalent to StartLoadAllResource=2, and the RRight button is equivalent to StartLoadAllResource=3

However, due to the limitation of the Android system on the running memory usage of applications, this will result in applications occupying more running memory and being more prone to crashes.

Details:
"!GameDreamFactory\游戏梦工厂&Mugen的教程\游戏梦工厂\1、说明、问题、教程\其它.txt"

**Comment by NuggetFangus** [comment]
Thank you very much!!!
