### ISSUE TITLE
Black screen bug

### ISSUE THREAD

**Issue by Lklkjddjd** [qingjun1991/GameDreamFactory#43]
When I just open the app after I put the CQJ.Libs it just show me a Black screen
Also I'm using in android 13

**Comment by qingjun1991** [comment]
1, Perhaps your installation steps were incorrect. Please make sure to install according to the steps in the video.
https://www.bilibili.com/video/BV1Kr4y127B3

2, Take a look at the error messages in this file "!GameDreamFactory/log.txt".

**Comment by Lklkjddjd** [comment]
From what I see I have done the steps correctly and
I can't find the log.txt file

**Comment by Lklkjddjd** [comment]
Also when I deleted the Formxtextures the app doesn't have the black screen but can't play

**Comment by qingjun1991** [comment]
It's possible that you haven't given the application permission.

**Comment by Lklkjddjd** [comment]
I gave the app all the permissions it asked for.

**Comment by qingjun1991** [comment]
That may be due to some files in this folder "/storage/emulated/0/!GameDreamFactory/CQJ.Libs" being lost or having outdated versions.

Please compress this folder and send it to me for analysis, "/storage/emulated/0/!GameDreamFactory", If the file is too large, please remove "/storage/emulated/0/!GameDreamFactory/chars" and "/storage/emulated/0/!GameDreamFactory/stages".

You can send it to GitHub or my email "1257526872@qq.com".

**Comment by Lklkjddjd** [comment]
[!GameDreamFactory.zip](https://github.com/user-attachments/files/18119724/GameDreamFactory.zip)

**Comment by qingjun1991** [comment]
This is just an update package, what you need is the main package.

**Comment by Lklkjddjd** [comment]
What do you mean by the main package?

**Comment by qingjun1991** [comment]
https://github.com/qingjun1991/GameDreamFactory/releases/tag/main

**Comment by Lklkjddjd** [comment]
Never mind I just checked and I had made a wrong step

**Comment by Lklkjddjd** [comment]
Now it's working
