### ISSUE TITLE
Stage viewer

### ISSUE THREAD

**Issue by NuggetFangus** [qingjun1991/GameDreamFactory#45]
How can i add stage viewer to my mugen?

**Comment by qingjun1991** [comment]
Stage Viewer is a Windows application.  So if you want to run it on your phone, use an emulator.

If you only want to preview stages, you can directly use this engine. The method is to use the original "!GameDreamFactory", and then put all your stages files into "!GameDreamFactory\stages", without changing "!GameDreamFactory\data\select.def", because these stages  will be automatically loaded, and then open the app and enter training mode. After selecting the characters, you can select the stages, and the stages will be displayed in the background of the select screen to achieve the preview effect.

**Comment by NuggetFangus** [comment]
Does it work with mugen 1.1?

**Comment by NuggetFangus** [comment]
The stage preview effect

**Comment by qingjun1991** [comment]
This feature is unique to this engine, which adds some code on top of Mugen. You can copy this code to your Mugen folder so that your Mugen also has this feature. Of course, you must use this engine to have the effect. but understanding the code is difficult. At least you need to understand some of the code in the Mugen tutorial, otherwise it will be difficult for you to achieve it.

**Comment by NuggetFangus** [comment]
In which folder i can find the code?

**Comment by qingjun1991** [comment]
> Does it work with mugen 1.1?

mugen 1.1 has two meanings, one is mugen 1.1 engine application and the other is mugen 1.1 folder.
I hope everyone can make it clear in the future. Because this is easily misunderstood.

**Comment by qingjun1991** [comment]
> In which folder i can find the code?

"!GameDreamFactory\data\system.def"
[Select Info]
+ Stage.Def="chars/道具/SelectScreen/kfm宽屏SelectScreen.def"
﻿
"!GameDreamFactory\chars\道具\SelectScreen"
﻿
The implementation principle is select screen load a stage, which loads an invisible character whose role is to change the current stage based on the stage you choose.
